/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as InviteMembershipIdRouteImport } from './routes/invite.$membershipId'
import { Route as AppWeatherIndexRouteImport } from './routes/_app/weather/index'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSeasonalIndexRouteImport } from './routes/_app/seasonal/index'
import { Route as AppMaintenanceIndexRouteImport } from './routes/_app/maintenance/index'
import { Route as AppGalleryIndexRouteImport } from './routes/_app/gallery/index'
import { Route as AppDocumentsIndexRouteImport } from './routes/_app/documents/index'
import { Route as AppContactsIndexRouteImport } from './routes/_app/contacts/index'
import { Route as AppCalendarIndexRouteImport } from './routes/_app/calendar/index'
import { Route as AppAssetsIndexRouteImport } from './routes/_app/assets/index'
import { Route as AppAnnouncementsIndexRouteImport } from './routes/_app/announcements/index'
import { Route as AppAnalyticsIndexRouteImport } from './routes/_app/analytics/index'
import { Route as AppTasksTodayRouteImport } from './routes/_app/tasks/today'
import { Route as AppTasksTemplatesRouteImport } from './routes/_app/tasks/templates'
import { Route as AppTasksTaskIdRouteImport } from './routes/_app/tasks/$taskId'
import { Route as AppSettingsWeatherRouteImport } from './routes/_app/settings/weather'
import { Route as AppSettingsRemindersRouteImport } from './routes/_app/settings/reminders'
import { Route as AppSettingsProfileRouteImport } from './routes/_app/settings/profile'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app/settings/notifications'
import { Route as AppSettingsMembersRouteImport } from './routes/_app/settings/members'
import { Route as AppSettingsHouseRouteImport } from './routes/_app/settings/house'
import { Route as AppSeasonalClosingRouteImport } from './routes/_app/seasonal/closing'
import { Route as AppMaintenanceNewRouteImport } from './routes/_app/maintenance/new'
import { Route as AppMaintenanceIssueIdRouteImport } from './routes/_app/maintenance/$issueId'
import { Route as AppGalleryPhotoIdRouteImport } from './routes/_app/gallery/$photoId'
import { Route as AppCalendarNewRouteImport } from './routes/_app/calendar/new'
import { Route as AppCalendarStayIdRouteImport } from './routes/_app/calendar/$stayId'
import { Route as AppAssetsNewRouteImport } from './routes/_app/assets/new'
import { Route as AppAssetsAssetIdRouteImport } from './routes/_app/assets/$assetId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const InviteMembershipIdRoute = InviteMembershipIdRouteImport.update({
  id: '/invite/$membershipId',
  path: '/invite/$membershipId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWeatherIndexRoute = AppWeatherIndexRouteImport.update({
  id: '/weather/',
  path: '/weather/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSeasonalIndexRoute = AppSeasonalIndexRouteImport.update({
  id: '/seasonal/',
  path: '/seasonal/',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceIndexRoute = AppMaintenanceIndexRouteImport.update({
  id: '/maintenance/',
  path: '/maintenance/',
  getParentRoute: () => AppRoute,
} as any)
const AppGalleryIndexRoute = AppGalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarIndexRoute = AppCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsIndexRoute = AppAnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsIndexRoute = AppAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTodayRoute = AppTasksTodayRouteImport.update({
  id: '/tasks/today',
  path: '/tasks/today',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTemplatesRoute = AppTasksTemplatesRouteImport.update({
  id: '/tasks/templates',
  path: '/tasks/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsWeatherRoute = AppSettingsWeatherRouteImport.update({
  id: '/settings/weather',
  path: '/settings/weather',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRemindersRoute = AppSettingsRemindersRouteImport.update({
  id: '/settings/reminders',
  path: '/settings/reminders',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsMembersRoute = AppSettingsMembersRouteImport.update({
  id: '/settings/members',
  path: '/settings/members',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsHouseRoute = AppSettingsHouseRouteImport.update({
  id: '/settings/house',
  path: '/settings/house',
  getParentRoute: () => AppRoute,
} as any)
const AppSeasonalClosingRoute = AppSeasonalClosingRouteImport.update({
  id: '/seasonal/closing',
  path: '/seasonal/closing',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceNewRoute = AppMaintenanceNewRouteImport.update({
  id: '/maintenance/new',
  path: '/maintenance/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintenanceIssueIdRoute = AppMaintenanceIssueIdRouteImport.update({
  id: '/maintenance/$issueId',
  path: '/maintenance/$issueId',
  getParentRoute: () => AppRoute,
} as any)
const AppGalleryPhotoIdRoute = AppGalleryPhotoIdRouteImport.update({
  id: '/gallery/$photoId',
  path: '/gallery/$photoId',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarNewRoute = AppCalendarNewRouteImport.update({
  id: '/calendar/new',
  path: '/calendar/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarStayIdRoute = AppCalendarStayIdRouteImport.update({
  id: '/calendar/$stayId',
  path: '/calendar/$stayId',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsNewRoute = AppAssetsNewRouteImport.update({
  id: '/assets/new',
  path: '/assets/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsAssetIdRoute = AppAssetsAssetIdRouteImport.update({
  id: '/assets/$assetId',
  path: '/assets/$assetId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/invite/$membershipId': typeof InviteMembershipIdRoute
  '/assets/$assetId': typeof AppAssetsAssetIdRoute
  '/assets/new': typeof AppAssetsNewRoute
  '/calendar/$stayId': typeof AppCalendarStayIdRoute
  '/calendar/new': typeof AppCalendarNewRoute
  '/gallery/$photoId': typeof AppGalleryPhotoIdRoute
  '/maintenance/$issueId': typeof AppMaintenanceIssueIdRoute
  '/maintenance/new': typeof AppMaintenanceNewRoute
  '/seasonal/closing': typeof AppSeasonalClosingRoute
  '/settings/house': typeof AppSettingsHouseRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/reminders': typeof AppSettingsRemindersRoute
  '/settings/weather': typeof AppSettingsWeatherRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/tasks/templates': typeof AppTasksTemplatesRoute
  '/tasks/today': typeof AppTasksTodayRoute
  '/analytics/': typeof AppAnalyticsIndexRoute
  '/announcements/': typeof AppAnnouncementsIndexRoute
  '/assets/': typeof AppAssetsIndexRoute
  '/calendar/': typeof AppCalendarIndexRoute
  '/contacts/': typeof AppContactsIndexRoute
  '/documents/': typeof AppDocumentsIndexRoute
  '/gallery/': typeof AppGalleryIndexRoute
  '/maintenance/': typeof AppMaintenanceIndexRoute
  '/seasonal/': typeof AppSeasonalIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
  '/weather/': typeof AppWeatherIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/invite/$membershipId': typeof InviteMembershipIdRoute
  '/': typeof AppIndexRoute
  '/assets/$assetId': typeof AppAssetsAssetIdRoute
  '/assets/new': typeof AppAssetsNewRoute
  '/calendar/$stayId': typeof AppCalendarStayIdRoute
  '/calendar/new': typeof AppCalendarNewRoute
  '/gallery/$photoId': typeof AppGalleryPhotoIdRoute
  '/maintenance/$issueId': typeof AppMaintenanceIssueIdRoute
  '/maintenance/new': typeof AppMaintenanceNewRoute
  '/seasonal/closing': typeof AppSeasonalClosingRoute
  '/settings/house': typeof AppSettingsHouseRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/profile': typeof AppSettingsProfileRoute
  '/settings/reminders': typeof AppSettingsRemindersRoute
  '/settings/weather': typeof AppSettingsWeatherRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/tasks/templates': typeof AppTasksTemplatesRoute
  '/tasks/today': typeof AppTasksTodayRoute
  '/analytics': typeof AppAnalyticsIndexRoute
  '/announcements': typeof AppAnnouncementsIndexRoute
  '/assets': typeof AppAssetsIndexRoute
  '/calendar': typeof AppCalendarIndexRoute
  '/contacts': typeof AppContactsIndexRoute
  '/documents': typeof AppDocumentsIndexRoute
  '/gallery': typeof AppGalleryIndexRoute
  '/maintenance': typeof AppMaintenanceIndexRoute
  '/seasonal': typeof AppSeasonalIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/tasks': typeof AppTasksIndexRoute
  '/weather': typeof AppWeatherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/invite/$membershipId': typeof InviteMembershipIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/assets/$assetId': typeof AppAssetsAssetIdRoute
  '/_app/assets/new': typeof AppAssetsNewRoute
  '/_app/calendar/$stayId': typeof AppCalendarStayIdRoute
  '/_app/calendar/new': typeof AppCalendarNewRoute
  '/_app/gallery/$photoId': typeof AppGalleryPhotoIdRoute
  '/_app/maintenance/$issueId': typeof AppMaintenanceIssueIdRoute
  '/_app/maintenance/new': typeof AppMaintenanceNewRoute
  '/_app/seasonal/closing': typeof AppSeasonalClosingRoute
  '/_app/settings/house': typeof AppSettingsHouseRoute
  '/_app/settings/members': typeof AppSettingsMembersRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/profile': typeof AppSettingsProfileRoute
  '/_app/settings/reminders': typeof AppSettingsRemindersRoute
  '/_app/settings/weather': typeof AppSettingsWeatherRoute
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/_app/tasks/templates': typeof AppTasksTemplatesRoute
  '/_app/tasks/today': typeof AppTasksTodayRoute
  '/_app/analytics/': typeof AppAnalyticsIndexRoute
  '/_app/announcements/': typeof AppAnnouncementsIndexRoute
  '/_app/assets/': typeof AppAssetsIndexRoute
  '/_app/calendar/': typeof AppCalendarIndexRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/documents/': typeof AppDocumentsIndexRoute
  '/_app/gallery/': typeof AppGalleryIndexRoute
  '/_app/maintenance/': typeof AppMaintenanceIndexRoute
  '/_app/seasonal/': typeof AppSeasonalIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
  '/_app/weather/': typeof AppWeatherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/invite/$membershipId'
    | '/assets/$assetId'
    | '/assets/new'
    | '/calendar/$stayId'
    | '/calendar/new'
    | '/gallery/$photoId'
    | '/maintenance/$issueId'
    | '/maintenance/new'
    | '/seasonal/closing'
    | '/settings/house'
    | '/settings/members'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/reminders'
    | '/settings/weather'
    | '/tasks/$taskId'
    | '/tasks/templates'
    | '/tasks/today'
    | '/analytics/'
    | '/announcements/'
    | '/assets/'
    | '/calendar/'
    | '/contacts/'
    | '/documents/'
    | '/gallery/'
    | '/maintenance/'
    | '/seasonal/'
    | '/settings/'
    | '/tasks/'
    | '/weather/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/invite/$membershipId'
    | '/'
    | '/assets/$assetId'
    | '/assets/new'
    | '/calendar/$stayId'
    | '/calendar/new'
    | '/gallery/$photoId'
    | '/maintenance/$issueId'
    | '/maintenance/new'
    | '/seasonal/closing'
    | '/settings/house'
    | '/settings/members'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/reminders'
    | '/settings/weather'
    | '/tasks/$taskId'
    | '/tasks/templates'
    | '/tasks/today'
    | '/analytics'
    | '/announcements'
    | '/assets'
    | '/calendar'
    | '/contacts'
    | '/documents'
    | '/gallery'
    | '/maintenance'
    | '/seasonal'
    | '/settings'
    | '/tasks'
    | '/weather'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/invite/$membershipId'
    | '/_app/'
    | '/_app/assets/$assetId'
    | '/_app/assets/new'
    | '/_app/calendar/$stayId'
    | '/_app/calendar/new'
    | '/_app/gallery/$photoId'
    | '/_app/maintenance/$issueId'
    | '/_app/maintenance/new'
    | '/_app/seasonal/closing'
    | '/_app/settings/house'
    | '/_app/settings/members'
    | '/_app/settings/notifications'
    | '/_app/settings/profile'
    | '/_app/settings/reminders'
    | '/_app/settings/weather'
    | '/_app/tasks/$taskId'
    | '/_app/tasks/templates'
    | '/_app/tasks/today'
    | '/_app/analytics/'
    | '/_app/announcements/'
    | '/_app/assets/'
    | '/_app/calendar/'
    | '/_app/contacts/'
    | '/_app/documents/'
    | '/_app/gallery/'
    | '/_app/maintenance/'
    | '/_app/seasonal/'
    | '/_app/settings/'
    | '/_app/tasks/'
    | '/_app/weather/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  InviteMembershipIdRoute: typeof InviteMembershipIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/$membershipId': {
      id: '/invite/$membershipId'
      path: '/invite/$membershipId'
      fullPath: '/invite/$membershipId'
      preLoaderRoute: typeof InviteMembershipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/weather/': {
      id: '/_app/weather/'
      path: '/weather'
      fullPath: '/weather/'
      preLoaderRoute: typeof AppWeatherIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seasonal/': {
      id: '/_app/seasonal/'
      path: '/seasonal'
      fullPath: '/seasonal/'
      preLoaderRoute: typeof AppSeasonalIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance/': {
      id: '/_app/maintenance/'
      path: '/maintenance'
      fullPath: '/maintenance/'
      preLoaderRoute: typeof AppMaintenanceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gallery/': {
      id: '/_app/gallery/'
      path: '/gallery'
      fullPath: '/gallery/'
      preLoaderRoute: typeof AppGalleryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/': {
      id: '/_app/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar/': {
      id: '/_app/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AppCalendarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/': {
      id: '/_app/assets/'
      path: '/assets'
      fullPath: '/assets/'
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/announcements/': {
      id: '/_app/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AppAnnouncementsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics/': {
      id: '/_app/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AppAnalyticsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/today': {
      id: '/_app/tasks/today'
      path: '/tasks/today'
      fullPath: '/tasks/today'
      preLoaderRoute: typeof AppTasksTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/templates': {
      id: '/_app/tasks/templates'
      path: '/tasks/templates'
      fullPath: '/tasks/templates'
      preLoaderRoute: typeof AppTasksTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/weather': {
      id: '/_app/settings/weather'
      path: '/settings/weather'
      fullPath: '/settings/weather'
      preLoaderRoute: typeof AppSettingsWeatherRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/reminders': {
      id: '/_app/settings/reminders'
      path: '/settings/reminders'
      fullPath: '/settings/reminders'
      preLoaderRoute: typeof AppSettingsRemindersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/profile': {
      id: '/_app/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/members': {
      id: '/_app/settings/members'
      path: '/settings/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/house': {
      id: '/_app/settings/house'
      path: '/settings/house'
      fullPath: '/settings/house'
      preLoaderRoute: typeof AppSettingsHouseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seasonal/closing': {
      id: '/_app/seasonal/closing'
      path: '/seasonal/closing'
      fullPath: '/seasonal/closing'
      preLoaderRoute: typeof AppSeasonalClosingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance/new': {
      id: '/_app/maintenance/new'
      path: '/maintenance/new'
      fullPath: '/maintenance/new'
      preLoaderRoute: typeof AppMaintenanceNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maintenance/$issueId': {
      id: '/_app/maintenance/$issueId'
      path: '/maintenance/$issueId'
      fullPath: '/maintenance/$issueId'
      preLoaderRoute: typeof AppMaintenanceIssueIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gallery/$photoId': {
      id: '/_app/gallery/$photoId'
      path: '/gallery/$photoId'
      fullPath: '/gallery/$photoId'
      preLoaderRoute: typeof AppGalleryPhotoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar/new': {
      id: '/_app/calendar/new'
      path: '/calendar/new'
      fullPath: '/calendar/new'
      preLoaderRoute: typeof AppCalendarNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar/$stayId': {
      id: '/_app/calendar/$stayId'
      path: '/calendar/$stayId'
      fullPath: '/calendar/$stayId'
      preLoaderRoute: typeof AppCalendarStayIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/new': {
      id: '/_app/assets/new'
      path: '/assets/new'
      fullPath: '/assets/new'
      preLoaderRoute: typeof AppAssetsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/$assetId': {
      id: '/_app/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof AppAssetsAssetIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAssetsAssetIdRoute: typeof AppAssetsAssetIdRoute
  AppAssetsNewRoute: typeof AppAssetsNewRoute
  AppCalendarStayIdRoute: typeof AppCalendarStayIdRoute
  AppCalendarNewRoute: typeof AppCalendarNewRoute
  AppGalleryPhotoIdRoute: typeof AppGalleryPhotoIdRoute
  AppMaintenanceIssueIdRoute: typeof AppMaintenanceIssueIdRoute
  AppMaintenanceNewRoute: typeof AppMaintenanceNewRoute
  AppSeasonalClosingRoute: typeof AppSeasonalClosingRoute
  AppSettingsHouseRoute: typeof AppSettingsHouseRoute
  AppSettingsMembersRoute: typeof AppSettingsMembersRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsRemindersRoute: typeof AppSettingsRemindersRoute
  AppSettingsWeatherRoute: typeof AppSettingsWeatherRoute
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
  AppTasksTemplatesRoute: typeof AppTasksTemplatesRoute
  AppTasksTodayRoute: typeof AppTasksTodayRoute
  AppAnalyticsIndexRoute: typeof AppAnalyticsIndexRoute
  AppAnnouncementsIndexRoute: typeof AppAnnouncementsIndexRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
  AppCalendarIndexRoute: typeof AppCalendarIndexRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
  AppGalleryIndexRoute: typeof AppGalleryIndexRoute
  AppMaintenanceIndexRoute: typeof AppMaintenanceIndexRoute
  AppSeasonalIndexRoute: typeof AppSeasonalIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
  AppWeatherIndexRoute: typeof AppWeatherIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAssetsAssetIdRoute: AppAssetsAssetIdRoute,
  AppAssetsNewRoute: AppAssetsNewRoute,
  AppCalendarStayIdRoute: AppCalendarStayIdRoute,
  AppCalendarNewRoute: AppCalendarNewRoute,
  AppGalleryPhotoIdRoute: AppGalleryPhotoIdRoute,
  AppMaintenanceIssueIdRoute: AppMaintenanceIssueIdRoute,
  AppMaintenanceNewRoute: AppMaintenanceNewRoute,
  AppSeasonalClosingRoute: AppSeasonalClosingRoute,
  AppSettingsHouseRoute: AppSettingsHouseRoute,
  AppSettingsMembersRoute: AppSettingsMembersRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsRemindersRoute: AppSettingsRemindersRoute,
  AppSettingsWeatherRoute: AppSettingsWeatherRoute,
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
  AppTasksTemplatesRoute: AppTasksTemplatesRoute,
  AppTasksTodayRoute: AppTasksTodayRoute,
  AppAnalyticsIndexRoute: AppAnalyticsIndexRoute,
  AppAnnouncementsIndexRoute: AppAnnouncementsIndexRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
  AppCalendarIndexRoute: AppCalendarIndexRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
  AppGalleryIndexRoute: AppGalleryIndexRoute,
  AppMaintenanceIndexRoute: AppMaintenanceIndexRoute,
  AppSeasonalIndexRoute: AppSeasonalIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
  AppWeatherIndexRoute: AppWeatherIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  InviteMembershipIdRoute: InviteMembershipIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
